allowBuilds:
  esbuild: true

approveBuildsAutomatically: true

minimumReleaseAgeExclude:
  - tmp@0.2.4
  - lodash@4.17.23
  - rollup@4.59.0
  - path-to-regexp@0.1.13
  - brace-expansion@1.1.13
  - yaml@2.8.3
  - lodash@4.17.24
  - vite@7.3.2
  - postcss@8.5.10
  - ws@8.20.1
  - uuid@11.1.1
  - qs@6.15.2
  - tmp@0.2.6
  - vitest@4.1.0
  - react-router@7.14.2
  - react-router@7.14.1
  - react-router@7.13.2
  - react-router@7.15.0
  - react-router@7.14.0

overrides:
  lodash@<=4.17.23: ^4.17.24
  lodash@>=4.0.0 <=4.17.22: ^4.17.23
  lodash@>=4.0.0 <=4.17.23: ^4.17.24
  qs@>=6.11.1 <=6.15.1: ^6.15.2
  react-router@>=7.0.0 <7.14.0: ^7.14.0
  react-router@>=7.0.0 <7.14.1: ^7.14.1
  react-router@>=7.0.0 <7.15.0: ^7.15.0
  react-router@>=7.0.0 <=7.14.1: ^7.14.2
  react-router@>=7.5.1 <7.13.2: ^7.13.2
  react-router@>=7.7.0 <7.13.2: ^7.13.2
  tmp@<0.2.6: ^0.2.6
  tmp@<=0.2.3: ^0.2.4
  uuid@<11.1.1: ^11.1.1
